# Generated by Django 5.2.6 on 2025-09-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('role', models.CharField(choices=[('教員', '教員'), ('実行委員長', '実行委員長'), ('委員長', '委員長'), ('その他', 'その他')], max_length=50, verbose_name='役職')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='ログイン日時')),
                ('committee', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属委員会')),
            ],
        ),
    ]
