# Generated by Django 5.2.6 on 2025-10-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrequest',
            name='class_exhibit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='担当クラス'),
        ),
        migrations.AddField(
            model_name='loginrequest',
            name='club',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所属部活動'),
        ),
        migrations.AlterField(
            model_name='loginrequest',
            name='role',
            field=models.CharField(choices=[('教員', '教員'), ('実行委員長', '実行委員長'), ('委員長', '委員長'), ('部活動関係者', '部活動関係者'), ('クラス展示関係者', 'クラス展示関係者')], max_length=50, verbose_name='役職'),
        ),
    ]
