# Generated by Django 5.2.6 on 2025-10-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginrequest_class_exhibit_loginrequest_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrequest',
            name='otp_code_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='OTPハッシュ'),
        ),
        migrations.AddField(
            model_name='loginrequest',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP有効期限'),
        ),
    ]
