# Generated by Django 5.2.6 on 2025-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='calculate_sum',
            field=models.BooleanField(default=False, verbose_name='合計を計算する'),
        ),
    ]
