# Generated by Django 5.2.6 on 2025-10-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='完了'),
        ),
    ]
